### ISSUE TITLE
[BUG] Unhandled Exception in script (Windows)

### ISSUE THREAD

**Issue by Thefinalpinkslip** [Bit-Scripts/APPIPTV_Freebox_et_HDHomeRun#2]
[BUG] Unhandled Exception in script (Windows)
The installer for windows wont start because of the error 
"Failed to execute script main due to unhandled exception: Failed to load dynlib/dll"

Traceback (most recent call last):
  File "main.py", line 11, in <module>
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "vlc.py", line 220, in <module>
  File "vlc.py", line 180, in find_lib
  File "PyInstaller\loader\pyimod03_ctypes.py", line 55, in __init__
pyimod03_ctypes.install.<locals>.PyInstallerImportError: Failed to load dynlib/dll '.\\libvlc.dll'. Most likely this dynlib/dll was not found when the application was frozen

**Comment by Paullux** [comment]
Bonjour,

Merci beaucoup pour votre retour et nous sommes désolés pour les désagréments rencontrés avec la version précédente de notre application sur Windows. Nous avons pris en compte votre problème et avons travaillé sur des améliorations significatives dans notre dernière mise à jour, la version 1.3.0.

**Voici ce que nous avons amélioré dans la version 1.3.0 :**

* **Gestion améliorée des bibliothèques dynamiques :** Nous avons apporté des modifications spécifiques pour s'assurer que les fichiers nécessaires comme libvlc.dll sont correctement chargés, ce qui devrait résoudre le problème que vous avez rencontré.
* **Installation simplifiée :** Des instructions plus claires et un processus d'installation amélioré pour éviter les problèmes lors du premier lancement.

**Pour tester la nouvelle version :**

1. Veuillez télécharger la dernière version (v1.3.0) depuis [lien de téléchargement](https://github.com/Bit-Scripts/APPIPTV_Freebox_et_HDHomeRun/releases/latest).
2. Désinstallez l'ancienne version de l'application avant d'installer la nouvelle pour éviter tout conflit potentiel (suppression de l'ancienne version).
3. Installez la nouvelle version en suivant les instructions fournies avec le téléchargement.

Nous serions ravis d'avoir vos retours sur cette nouvelle version. Si vous rencontrez toujours des problèmes ou si vous avez d'autres commentaires, n'hésitez pas à nous contacter. Votre feedback est essentiel pour nous aider à améliorer continuellement.

Merci encore pour votre soutien et votre patience.

Cordialement,
Paul W, de Bit-Scripts

**Comment by Thefinalpinkslip** [comment]
Thank you Paul for your quick response sadly after entering a m3u a unexpected error occured and now the app is throwing a error "unhandled error in script2" I've posted the error below for some information cheers.

Traceback (most recent call last):
  File "main.py", line 135, in <module>
  File "main.py", line 126, in main
  File "src\MainWindow.py", line 115, in __init__
    self.initUI()
  File "src\MainWindow.py", line 397, in initUI
    self.loadPlaylists()
  File "src\MainWindow.py", line 530, in loadPlaylists
    self.displayChannels(merged_channels)
  File "src\MainWindow.py", line 546, in displayChannels
    for name, url in sorted(channels.items(), key=lambda x: int(x[0].split(" - ")[0])):
  File "src\MainWindow.py", line 546, in <lambda>
    for name, url in sorted(channels.items(), key=lambda x: int(x[0].split(" - ")[0])):
ValueError: invalid literal for int() with base 10: 'SPFL'

**Comment by Paullux** [comment]
### Français :
  
Bonjour,  
  
Merci pour votre retour et désolé pour les désagréments rencontrés. Nous avons identifié la source de l'erreur que vous avez signalée. Le problème provenait d'une tentative de tri des chaînes utilisant des préfixes numériques, alors que certaines chaînes n'ont pas de préfixe numérique valide.  
  
Nous avons apporté les modifications suivantes au code pour résoudre ce problème :  
  
- Nous avons ajouté une fonction `get_channel_number` pour extraire le numéro de chaîne ou retourner une valeur par défaut si ce n'est pas un nombre.  
- Nous avons mis à jour le tri des chaînes pour utiliser cette nouvelle fonction, assurant ainsi que les chaînes sans numéro valide ne provoquent plus d'erreurs.  
   
Ces modifications ont été testées et devraient corriger le problème que vous avez rencontré. Merci de mettre à jour votre application avec la dernière version pour bénéficier de ces corrections.  
  
### English :
     
Hello,    
    
Thank you for your feedback and sorry for the inconvenience you experienced. We have identified the source of the error you reported. The issue was due to an attempt to sort channels using numerical prefixes, while some channels did not have a valid numerical prefix.  
   
We have made the following changes to the code to resolve this issue:  
  
- Added a `get_channel_number` function to extract the channel number or return a default value if it's not a number.  
- Updated the channel sorting to use this new function, ensuring that channels without a valid number no longer cause errors.  
  
These changes have been tested and should fix the issue you encountered. Please update your application to the latest version to benefit from these fixes.
